import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/driver_profile.dart';
import '../models/trip.dart';
import '../models/parking.dart';
import '../models/accident.dart';
import '../models/violation.dart';

class FirestoreService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // Generic method to fetch a list of items from a collection
  Future<List<T>> getCollection<T>({
    required String collectionPath,
    required T Function(Map<String, dynamic> data, String documentId) builder,
  }) async {
    try {
      final QuerySnapshot snapshot = await _db.collection(collectionPath).get();
      return snapshot.docs
          .map((doc) => builder(doc.data() as Map<String, dynamic>, doc.id))
          .toList();
    } catch (e) {
      print('Error fetching collection \$collectionPath: \$e');
      return [];
    }
  }

  // Generate Dummy Data for Testing
  Future<void> generateDummyData(String userId) async {
    try {
      // 1. Driver Profile
      final profileRef = _db.collection('drivers').doc(userId);
      if (!(await profileRef.get()).exists) {
        await profileRef.set(DriverProfile(
          id: userId,
          name: 'John Doe',
          email: 'driver@test.com',
          vehicleType: 'Car',
          licenseNumber: 'DL123456789',
          rating: 4.8,
        ).toJson());
      }

      // 2. Trips
      await _db.collection('trips').add(Trip(
        id: '', // Will be generated by Firestore
        driverId: userId,
        startLocation: 'Point A',
        endLocation: 'Point B',
        startTime: DateTime.now().subtract(const Duration(days: 1)),
        endTime: DateTime.now().subtract(const Duration(hours: 23)),
        distance: 15.5,
        status: 'completed',
      ).toJson());

      // 3. Parking
      await _db.collection('parking').add(Parking(
        id: '',
        locationName: 'City Center Mall Parking',
        latitude: 34.0522,
        longitude: -118.2437,
        status: 'departed',
        parkedTime: DateTime.now().subtract(const Duration(hours: 5)),
        departedTime: DateTime.now().subtract(const Duration(hours: 3)),
        cost: 10.0,
      ).toJson());

      // 4. Accidents
      await _db.collection('accidents').add(Accident(
        id: '',
        driverId: userId,
        timestamp: DateTime.now().subtract(const Duration(days: 30)),
        location: 'Highway 101',
        severity: 'minor',
        description: 'Fender bender due to sudden braking',
      ).toJson());

      // 5. Violations
      await _db.collection('violations').add(Violation(
        id: '',
        driverId: userId,
        timestamp: DateTime.now().subtract(const Duration(days: 15)),
        type: 'speeding',
        location: 'Main Street Zone 4',
        fineAmount: 150.0,
        status: 'unpaid',
      ).toJson());

      print('Dummy data generated successfully');
    } catch (e) {
      print('Error generating dummy data: \$e');
    }
  }
}
