// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jYuTUAso7ZIjkHLEl2VQotN4V9En42M',
    appId: '1:593255202670:web:cfb96c069cf55f4cf80b7f',
    messagingSenderId: '593255202670',
    projectId: 'driver-mob-app-utms-766b3',
    authDomain: 'driver-mob-app-utms-766b3.firebaseapp.com',
    storageBucket: 'driver-mob-app-utms-766b3.firebasestorage.app',
    measurementId: 'G-1XEG2WQMJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCieg_WtShZh1mk2Jo0oqQtcBmQNO7m5s',
    appId: '1:593255202670:android:ec75c84cb4da4d61f80b7f',
    messagingSenderId: '593255202670',
    projectId: 'driver-mob-app-utms-766b3',
    storageBucket: 'driver-mob-app-utms-766b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3EblHidsq6A0C4PkZOwZWsVP0e38gDRw',
    appId: '1:593255202670:ios:61ca57d314831adff80b7f',
    messagingSenderId: '593255202670',
    projectId: 'driver-mob-app-utms-766b3',
    storageBucket: 'driver-mob-app-utms-766b3.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3EblHidsq6A0C4PkZOwZWsVP0e38gDRw',
    appId: '1:593255202670:ios:61ca57d314831adff80b7f',
    messagingSenderId: '593255202670',
    projectId: 'driver-mob-app-utms-766b3',
    storageBucket: 'driver-mob-app-utms-766b3.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jYuTUAso7ZIjkHLEl2VQotN4V9En42M',
    appId: '1:593255202670:web:96989f925bc5a093f80b7f',
    messagingSenderId: '593255202670',
    projectId: 'driver-mob-app-utms-766b3',
    authDomain: 'driver-mob-app-utms-766b3.firebaseapp.com',
    storageBucket: 'driver-mob-app-utms-766b3.firebasestorage.app',
    measurementId: 'G-R6BS5QNZFN',
  );
}
